# ===============================
# CONFIGURACIÓN SQL SERVER (NUBE/AZURE)
# ===============================
# Usamos las variables definidas en el archivo .env
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


# CONFIGURACIÓN DE JPA / HIBERNATE

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# CONFIGURACIÓN SEGURIDAD JWT

jwt.secret=${TOKEN_JWT_SECRET}